# Generated by Django 5.2.9 on 2025-12-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_description_contact_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phonenumber',
            field=models.IntegerField(max_length=10),
        ),
    ]
